------------------------------------------ My Include Config Files ------------------------------------------

require("user.general")
require("user.keymaps")
require("user.telescope")
require("user.nvim-options")
require("user.nvim-scrool")
-- reqq:qqq
--
-- <t_€ý>hcall v:lua.cmp.utils.feedkeys.call.run(1)
-- Ã½uire("user.nvim-noice")
require("user.formatOnSave")
require("user.autocommands")
require("user.copilot")
-- require("user.ufo")
-- require("user.nui")
require("user.preview")
-- require("user.nvim-noice")
require("user.nvim-multiple-cursor")
require("user.magma")
require("user.jupyter")
require("user.which_keymap")
-- require("user.toggle_term")
require("user.icons")
require("user.bookmark")
require("user.todo_comments")
require("user.symbols_outline")
require("user.sniprun")
require("user.tabnine")
require("user.jupynium")
require("user.markdown")
require("user.vs-code")
-- require("user.functions")

----------------------------------------- My Include Config Files ------------------------------------------
